### ISSUE TITLE
bad name

### ISSUE THREAD

**Issue by nepster-web** [yii-dream-team/yii2-perfect-money#2]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package yii-dream-team/yii2-perfect-money could not be found
 in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

---

https://github.com/yii-dream-team/yii2-perfect-money/pull/1

**Comment by metalagman** [comment]
version 1.0.0 is released, should install fine in minimum-stability: stable
